
use_frameworks!
inhibit_all_warnings!

target 'IMPBaseOperations' do
    pod 'SnapKit'
    pod 'ObjectMapper'
    #pod 'OpenCV'
    #pod 'IMProcessing', :path => '../../../'
end


post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['DYLIB_COMPATIBILITY_VERSION'] = ''
            config.build_settings['ENABLE_BITCODE'] = 'YES'
        end
    end
end
