
use_frameworks!
inhibit_all_warnings!

platform :osx, '10.13'

target 'IMPColorSpacesTest' do
    #pod 'Surge', :git => 'https://github.com/dnevera/Surge'
    pod 'Surge', :path => '../../../../Surge'
    pod 'IMProcessing', :path => '../../../'
end


post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['DYLIB_COMPATIBILITY_VERSION'] = ''
        end
    end
end
