
use_frameworks!

target 'IMPPatchDetector' do
    platform :osx, '10.13'
    pod 'SnapKit' 
    pod 'Surge', :git => 'https://github.com/dnevera/Surge.git', :branch => 'develop-swift4'
    pod 'IMProcessing', :path => '../../..'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['DYLIB_COMPATIBILITY_VERSION'] = ''
            config.build_settings['ENABLE_BITCODE'] = 'NO'
        end
    end
end

