use_frameworks!
inhibit_all_warnings!

target 'IMPCameraManager' do
    pod 'SnapKit'
    pod 'ObjectMapper'
    pod 'IMProcessing', :path => '../../../', :configurations => ['Debug']
end


post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            #config.build_settings['DYLIB_COMPATIBILITY_VERSION'] = ''
            config.build_settings['ENABLE_BITCODE'] = 'NO'
            config.build_settings['OTHER_SWIFT_FLAGS'] = '-DDEBUG'
        end
    end
end

